[[headers]]
  for = "/*"
  [headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
  publish = "build"
  command = "npm run build:netlify"
[context.production]
  command = "ng build --configuration=production --deploy-url=https://erkenningen-module-manage-specialties.netlify.app/"
[context.acceptance]
  command = "ng build --configuration=acceptance --deploy-url=${DEPLOY_PRIME_URL}"
[context.develop]
  command = "ng build --configuration=develop"
[context.deploy-preview]
  command = "ng build --configuration=acceptance --deploy-url=$DEPLOY_PRIME_URL"
