[[headers]]
  for = "/*"
  [headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
  publish = "build"
  command = "npm run build:netlify"
[context.production]
  command = "ng build --configuration=production"
[context.acceptance]
  command = "ng build --configuration=acceptance"
[context.develop]
  command = "ng build --configuration=develop"
[context.deploy-preview]
  command = "ng build --configuration=acceptance"
