[[headers]]
  for = "/*"
  [headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
  publish = "build"
  command = "npm run build:netlify"
[context.production]
  command = "ng build --configuration=production --deploy-url=${DEPLOY_PRIME_URL}/"
[context.acceptance]
  command = "ng build --configuration=acceptance --deploy-url=${DEPLOY_PRIME_URL}/"
[context.develop]
  command = "ng build --configuration=develop --deploy-url=${DEPLOY_PRIME_URL}/"
[context.deploy-preview]
  command = "ng build --configuration=acceptance --deploy-url=${DEPLOY_PRIME_URL}/"
